<?php

namespace Tests\Feature;

use Illuminate\Foundation\Testing\RefreshDatabase;
use Tests\TestCase;

class ReadThreadTest extends TestCase
{
    use RefreshDatabase;

    public function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub

        $this->thread = factory('App\Thread')->create();
    }

    public function test_user_can_browse_threads()
    {

        $this->get('/threads')->assertSee($this->thread->title);

    }

    function test_user_can_see_single_thread()
    {

        $this->get($this->thread->path())->assertSee($this->thread->title);

    }

    function test_user_can_read_replies_associated_with_thread()
    {
        $reply = factory('App\Reply')->create(['thread_id' => $this->thread->id])->body;
        $this->get($this->thread->path())
            ->assertSee($this->thread->replies[0]->body, $reply);
    }


    // 글 마다 각자의 채널이 존재
    function test_user_can_filter_threads_according_to_a_tag()
    {

        $this->withoutExceptionHandling();

        $channel = factory('App\Channel')->create();

        $threadInChannel = create('App\Thread', ['channel_id' => $channel->id]);

        $threadNotInChannel = create('App\Thread');

        $this->get('/threads/' . $channel->slug)
            ->assertSee($threadInChannel->title)
            ->assertDontSee($threadNotInChannel->title);
    }

    function test_user_can_filter_thread_by_username()
    {
        $this->withoutExceptionHandling();

        $this->signIn(create('App\User', ['name' => 'JohnDoe']));

        $threadByJohn = create('App\Thread', ['user_id' => auth()->id()]);

        $threadNotByJohn = create('App\Thread');

        $this->get('threads?by=JohnDoe')
            ->assertSee($threadByJohn->title)
            ->assertDontSee($threadNotByJohn->title);
    }

    function test_user_can_filter_threads_by_popularity()
    {
        $threadWithTwoReplies =  create('App\Thread');
        create('App\Reply', ['thread_id' => $threadWithTwoReplies], 2);

        $threadWithThreeReplies =  create('App\Thread');
        create('App\Reply', ['thread_id' => $threadWithThreeReplies], 3);

        $threadWithNoReplies =  $this->thread;

        $response = $this->getJson('threads?popular=1')->json();

        $this->assertEquals([3, 2, 0], array_column($response, 'replies_count'));
    }

}
